/*
 * ******************************************************************************
 *   Copyright 2014-2015 Spectra Logic Corporation. All Rights Reserved.
 *   Licensed under the Apache License, Version 2.0 (the "License"). You may not use
 *   this file except in compliance with the License. A copy of the License is located at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 *   or in the "license" file accompanying this file.
 *   This file is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 *   CONDITIONS OF ANY KIND, either express or implied. See the License for the
 *   specific language governing permissions and limitations under the License.
 * ****************************************************************************
 */

// This code is auto-generated, do not modify
package com.spectralogic.ds3client;

import com.spectralogic.ds3client.commands.*;
import com.spectralogic.ds3client.commands.spectrads3.*;
import com.spectralogic.ds3client.commands.spectrads3.notifications.*;
import com.spectralogic.ds3client.models.Ds3Node;
import com.spectralogic.ds3client.networking.ConnectionDetails;

import java.io.Closeable;
import java.io.IOException;
import java.security.SignatureException;

public interface Ds3Client extends Closeable {

    ConnectionDetails getConnectionDetails();

    AbortMultiPartUploadResponse abortMultiPartUpload(AbortMultiPartUploadRequest request)
            throws IOException, SignatureException;
    CompleteMultiPartUploadResponse completeMultiPartUpload(CompleteMultiPartUploadRequest request)
            throws IOException, SignatureException;
    PutBucketResponse putBucket(PutBucketRequest request)
            throws IOException, SignatureException;
    PutMultiPartUploadPartResponse putMultiPartUploadPart(PutMultiPartUploadPartRequest request)
            throws IOException, SignatureException;
    PutObjectResponse putObject(PutObjectRequest request)
            throws IOException, SignatureException;
    DeleteBucketResponse deleteBucket(DeleteBucketRequest request)
            throws IOException, SignatureException;
    DeleteObjectResponse deleteObject(DeleteObjectRequest request)
            throws IOException, SignatureException;
    DeleteObjectsResponse deleteObjects(DeleteObjectsRequest request)
            throws IOException, SignatureException;
    GetBucketResponse getBucket(GetBucketRequest request)
            throws IOException, SignatureException;
    GetServiceResponse getService(GetServiceRequest request)
            throws IOException, SignatureException;
    HeadBucketResponse headBucket(HeadBucketRequest request)
            throws IOException, SignatureException;
    HeadObjectResponse headObject(HeadObjectRequest request)
            throws IOException, SignatureException;
    InitiateMultiPartUploadResponse initiateMultiPartUpload(InitiateMultiPartUploadRequest request)
            throws IOException, SignatureException;
    ListMultiPartUploadPartsResponse listMultiPartUploadParts(ListMultiPartUploadPartsRequest request)
            throws IOException, SignatureException;
    ListMultiPartUploadsResponse listMultiPartUploads(ListMultiPartUploadsRequest request)
            throws IOException, SignatureException;
    PutBucketAclForGroupSpectraS3Response putBucketAclForGroupSpectraS3(PutBucketAclForGroupSpectraS3Request request)
            throws IOException, SignatureException;
    PutBucketAclForUserSpectraS3Response putBucketAclForUserSpectraS3(PutBucketAclForUserSpectraS3Request request)
            throws IOException, SignatureException;
    PutDataPolicyAclForGroupSpectraS3Response putDataPolicyAclForGroupSpectraS3(PutDataPolicyAclForGroupSpectraS3Request request)
            throws IOException, SignatureException;
    PutDataPolicyAclForUserSpectraS3Response putDataPolicyAclForUserSpectraS3(PutDataPolicyAclForUserSpectraS3Request request)
            throws IOException, SignatureException;
    PutGlobalBucketAclForGroupSpectraS3Response putGlobalBucketAclForGroupSpectraS3(PutGlobalBucketAclForGroupSpectraS3Request request)
            throws IOException, SignatureException;
    PutGlobalBucketAclForUserSpectraS3Response putGlobalBucketAclForUserSpectraS3(PutGlobalBucketAclForUserSpectraS3Request request)
            throws IOException, SignatureException;
    PutGlobalDataPolicyAclForGroupSpectraS3Response putGlobalDataPolicyAclForGroupSpectraS3(PutGlobalDataPolicyAclForGroupSpectraS3Request request)
            throws IOException, SignatureException;
    PutGlobalDataPolicyAclForUserSpectraS3Response putGlobalDataPolicyAclForUserSpectraS3(PutGlobalDataPolicyAclForUserSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteBucketAclSpectraS3Response deleteBucketAclSpectraS3(DeleteBucketAclSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteDataPolicyAclSpectraS3Response deleteDataPolicyAclSpectraS3(DeleteDataPolicyAclSpectraS3Request request)
            throws IOException, SignatureException;
    GetBucketAclSpectraS3Response getBucketAclSpectraS3(GetBucketAclSpectraS3Request request)
            throws IOException, SignatureException;
    GetBucketAclsSpectraS3Response getBucketAclsSpectraS3(GetBucketAclsSpectraS3Request request)
            throws IOException, SignatureException;
    GetDataPolicyAclSpectraS3Response getDataPolicyAclSpectraS3(GetDataPolicyAclSpectraS3Request request)
            throws IOException, SignatureException;
    GetDataPolicyAclsSpectraS3Response getDataPolicyAclsSpectraS3(GetDataPolicyAclsSpectraS3Request request)
            throws IOException, SignatureException;
    PutBucketSpectraS3Response putBucketSpectraS3(PutBucketSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteBucketSpectraS3Response deleteBucketSpectraS3(DeleteBucketSpectraS3Request request)
            throws IOException, SignatureException;
    GetBucketSpectraS3Response getBucketSpectraS3(GetBucketSpectraS3Request request)
            throws IOException, SignatureException;
    GetBucketsSpectraS3Response getBucketsSpectraS3(GetBucketsSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyBucketSpectraS3Response modifyBucketSpectraS3(ModifyBucketSpectraS3Request request)
            throws IOException, SignatureException;
    ForceFullCacheReclaimSpectraS3Response forceFullCacheReclaimSpectraS3(ForceFullCacheReclaimSpectraS3Request request)
            throws IOException, SignatureException;
    GetCacheFilesystemSpectraS3Response getCacheFilesystemSpectraS3(GetCacheFilesystemSpectraS3Request request)
            throws IOException, SignatureException;
    GetCacheFilesystemsSpectraS3Response getCacheFilesystemsSpectraS3(GetCacheFilesystemsSpectraS3Request request)
            throws IOException, SignatureException;
    GetCacheStateSpectraS3Response getCacheStateSpectraS3(GetCacheStateSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyCacheFilesystemSpectraS3Response modifyCacheFilesystemSpectraS3(ModifyCacheFilesystemSpectraS3Request request)
            throws IOException, SignatureException;
    GetBucketCapacitySummarySpectraS3Response getBucketCapacitySummarySpectraS3(GetBucketCapacitySummarySpectraS3Request request)
            throws IOException, SignatureException;
    GetStorageDomainCapacitySummarySpectraS3Response getStorageDomainCapacitySummarySpectraS3(GetStorageDomainCapacitySummarySpectraS3Request request)
            throws IOException, SignatureException;
    GetSystemCapacitySummarySpectraS3Response getSystemCapacitySummarySpectraS3(GetSystemCapacitySummarySpectraS3Request request)
            throws IOException, SignatureException;
    GetDataPathBackendSpectraS3Response getDataPathBackendSpectraS3(GetDataPathBackendSpectraS3Request request)
            throws IOException, SignatureException;
    GetDataPlannerBlobStoreTasksSpectraS3Response getDataPlannerBlobStoreTasksSpectraS3(GetDataPlannerBlobStoreTasksSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyDataPathBackendSpectraS3Response modifyDataPathBackendSpectraS3(ModifyDataPathBackendSpectraS3Request request)
            throws IOException, SignatureException;
    PutDataPersistenceRuleSpectraS3Response putDataPersistenceRuleSpectraS3(PutDataPersistenceRuleSpectraS3Request request)
            throws IOException, SignatureException;
    PutDataPolicySpectraS3Response putDataPolicySpectraS3(PutDataPolicySpectraS3Request request)
            throws IOException, SignatureException;
    PutDataReplicationRuleSpectraS3Response putDataReplicationRuleSpectraS3(PutDataReplicationRuleSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteDataPersistenceRuleSpectraS3Response deleteDataPersistenceRuleSpectraS3(DeleteDataPersistenceRuleSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteDataPolicySpectraS3Response deleteDataPolicySpectraS3(DeleteDataPolicySpectraS3Request request)
            throws IOException, SignatureException;
    DeleteDataReplicationRuleSpectraS3Response deleteDataReplicationRuleSpectraS3(DeleteDataReplicationRuleSpectraS3Request request)
            throws IOException, SignatureException;
    GetDataPersistenceRuleSpectraS3Response getDataPersistenceRuleSpectraS3(GetDataPersistenceRuleSpectraS3Request request)
            throws IOException, SignatureException;
    GetDataPersistenceRulesSpectraS3Response getDataPersistenceRulesSpectraS3(GetDataPersistenceRulesSpectraS3Request request)
            throws IOException, SignatureException;
    GetDataPoliciesSpectraS3Response getDataPoliciesSpectraS3(GetDataPoliciesSpectraS3Request request)
            throws IOException, SignatureException;
    GetDataPolicySpectraS3Response getDataPolicySpectraS3(GetDataPolicySpectraS3Request request)
            throws IOException, SignatureException;
    GetDataReplicationRuleSpectraS3Response getDataReplicationRuleSpectraS3(GetDataReplicationRuleSpectraS3Request request)
            throws IOException, SignatureException;
    GetDataReplicationRulesSpectraS3Response getDataReplicationRulesSpectraS3(GetDataReplicationRulesSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyDataPersistenceRuleSpectraS3Response modifyDataPersistenceRuleSpectraS3(ModifyDataPersistenceRuleSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyDataPolicySpectraS3Response modifyDataPolicySpectraS3(ModifyDataPolicySpectraS3Request request)
            throws IOException, SignatureException;
    ModifyDataReplicationRuleSpectraS3Response modifyDataReplicationRuleSpectraS3(ModifyDataReplicationRuleSpectraS3Request request)
            throws IOException, SignatureException;
    GetDegradedBucketsSpectraS3Response getDegradedBucketsSpectraS3(GetDegradedBucketsSpectraS3Request request)
            throws IOException, SignatureException;
    GetDegradedDataPersistenceRulesSpectraS3Response getDegradedDataPersistenceRulesSpectraS3(GetDegradedDataPersistenceRulesSpectraS3Request request)
            throws IOException, SignatureException;
    GetDegradedDataReplicationRulesSpectraS3Response getDegradedDataReplicationRulesSpectraS3(GetDegradedDataReplicationRulesSpectraS3Request request)
            throws IOException, SignatureException;
    PutGroupGroupMemberSpectraS3Response putGroupGroupMemberSpectraS3(PutGroupGroupMemberSpectraS3Request request)
            throws IOException, SignatureException;
    PutGroupSpectraS3Response putGroupSpectraS3(PutGroupSpectraS3Request request)
            throws IOException, SignatureException;
    PutUserGroupMemberSpectraS3Response putUserGroupMemberSpectraS3(PutUserGroupMemberSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteGroupMemberSpectraS3Response deleteGroupMemberSpectraS3(DeleteGroupMemberSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteGroupSpectraS3Response deleteGroupSpectraS3(DeleteGroupSpectraS3Request request)
            throws IOException, SignatureException;
    GetGroupMemberSpectraS3Response getGroupMemberSpectraS3(GetGroupMemberSpectraS3Request request)
            throws IOException, SignatureException;
    GetGroupMembersSpectraS3Response getGroupMembersSpectraS3(GetGroupMembersSpectraS3Request request)
            throws IOException, SignatureException;
    GetGroupSpectraS3Response getGroupSpectraS3(GetGroupSpectraS3Request request)
            throws IOException, SignatureException;
    GetGroupsSpectraS3Response getGroupsSpectraS3(GetGroupsSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyGroupSpectraS3Response modifyGroupSpectraS3(ModifyGroupSpectraS3Request request)
            throws IOException, SignatureException;
    VerifyUserIsMemberOfGroupSpectraS3Response verifyUserIsMemberOfGroupSpectraS3(VerifyUserIsMemberOfGroupSpectraS3Request request)
            throws IOException, SignatureException;
    AllocateJobChunkSpectraS3Response allocateJobChunkSpectraS3(AllocateJobChunkSpectraS3Request request)
            throws IOException, SignatureException;
    CancelAllJobsSpectraS3Response cancelAllJobsSpectraS3(CancelAllJobsSpectraS3Request request)
            throws IOException, SignatureException;
    CancelJobSpectraS3Response cancelJobSpectraS3(CancelJobSpectraS3Request request)
            throws IOException, SignatureException;
    ClearAllCanceledJobsSpectraS3Response clearAllCanceledJobsSpectraS3(ClearAllCanceledJobsSpectraS3Request request)
            throws IOException, SignatureException;
    ClearAllCompletedJobsSpectraS3Response clearAllCompletedJobsSpectraS3(ClearAllCompletedJobsSpectraS3Request request)
            throws IOException, SignatureException;
    GetBulkJobSpectraS3Response getBulkJobSpectraS3(GetBulkJobSpectraS3Request request)
            throws IOException, SignatureException;
    PutBulkJobSpectraS3Response putBulkJobSpectraS3(PutBulkJobSpectraS3Request request)
            throws IOException, SignatureException;
    VerifyBulkJobSpectraS3Response verifyBulkJobSpectraS3(VerifyBulkJobSpectraS3Request request)
            throws IOException, SignatureException;
    GetActiveJobSpectraS3Response getActiveJobSpectraS3(GetActiveJobSpectraS3Request request)
            throws IOException, SignatureException;
    GetActiveJobsSpectraS3Response getActiveJobsSpectraS3(GetActiveJobsSpectraS3Request request)
            throws IOException, SignatureException;
    GetCanceledJobSpectraS3Response getCanceledJobSpectraS3(GetCanceledJobSpectraS3Request request)
            throws IOException, SignatureException;
    GetCanceledJobsSpectraS3Response getCanceledJobsSpectraS3(GetCanceledJobsSpectraS3Request request)
            throws IOException, SignatureException;
    GetCompletedJobSpectraS3Response getCompletedJobSpectraS3(GetCompletedJobSpectraS3Request request)
            throws IOException, SignatureException;
    GetCompletedJobsSpectraS3Response getCompletedJobsSpectraS3(GetCompletedJobsSpectraS3Request request)
            throws IOException, SignatureException;
    GetJobChunkSpectraS3Response getJobChunkSpectraS3(GetJobChunkSpectraS3Request request)
            throws IOException, SignatureException;
    GetJobChunksReadyForClientProcessingSpectraS3Response getJobChunksReadyForClientProcessingSpectraS3(GetJobChunksReadyForClientProcessingSpectraS3Request request)
            throws IOException, SignatureException;
    GetJobSpectraS3Response getJobSpectraS3(GetJobSpectraS3Request request)
            throws IOException, SignatureException;
    GetJobsSpectraS3Response getJobsSpectraS3(GetJobsSpectraS3Request request)
            throws IOException, SignatureException;
    GetPutJobToReplicateSpectraS3Response getPutJobToReplicateSpectraS3(GetPutJobToReplicateSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyJobSpectraS3Response modifyJobSpectraS3(ModifyJobSpectraS3Request request)
            throws IOException, SignatureException;
    ReplicatePutJobSpectraS3Response replicatePutJobSpectraS3(ReplicatePutJobSpectraS3Request request)
            throws IOException, SignatureException;
    TruncateAllJobsSpectraS3Response truncateAllJobsSpectraS3(TruncateAllJobsSpectraS3Request request)
            throws IOException, SignatureException;
    TruncateJobSpectraS3Response truncateJobSpectraS3(TruncateJobSpectraS3Request request)
            throws IOException, SignatureException;
    GetNodeSpectraS3Response getNodeSpectraS3(GetNodeSpectraS3Request request)
            throws IOException, SignatureException;
    GetNodesSpectraS3Response getNodesSpectraS3(GetNodesSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyNodeSpectraS3Response modifyNodeSpectraS3(ModifyNodeSpectraS3Request request)
            throws IOException, SignatureException;
    PutDs3TargetFailureNotificationRegistrationSpectraS3Response putDs3TargetFailureNotificationRegistrationSpectraS3(PutDs3TargetFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    PutJobCompletedNotificationRegistrationSpectraS3Response putJobCompletedNotificationRegistrationSpectraS3(PutJobCompletedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    PutJobCreatedNotificationRegistrationSpectraS3Response putJobCreatedNotificationRegistrationSpectraS3(PutJobCreatedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    PutObjectCachedNotificationRegistrationSpectraS3Response putObjectCachedNotificationRegistrationSpectraS3(PutObjectCachedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    PutObjectLostNotificationRegistrationSpectraS3Response putObjectLostNotificationRegistrationSpectraS3(PutObjectLostNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    PutObjectPersistedNotificationRegistrationSpectraS3Response putObjectPersistedNotificationRegistrationSpectraS3(PutObjectPersistedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    PutPoolFailureNotificationRegistrationSpectraS3Response putPoolFailureNotificationRegistrationSpectraS3(PutPoolFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    PutStorageDomainFailureNotificationRegistrationSpectraS3Response putStorageDomainFailureNotificationRegistrationSpectraS3(PutStorageDomainFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    PutSystemFailureNotificationRegistrationSpectraS3Response putSystemFailureNotificationRegistrationSpectraS3(PutSystemFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    PutTapeFailureNotificationRegistrationSpectraS3Response putTapeFailureNotificationRegistrationSpectraS3(PutTapeFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    PutTapePartitionFailureNotificationRegistrationSpectraS3Response putTapePartitionFailureNotificationRegistrationSpectraS3(PutTapePartitionFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteDs3TargetFailureNotificationRegistrationSpectraS3Response deleteDs3TargetFailureNotificationRegistrationSpectraS3(DeleteDs3TargetFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteJobCompletedNotificationRegistrationSpectraS3Response deleteJobCompletedNotificationRegistrationSpectraS3(DeleteJobCompletedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteJobCreatedNotificationRegistrationSpectraS3Response deleteJobCreatedNotificationRegistrationSpectraS3(DeleteJobCreatedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteObjectCachedNotificationRegistrationSpectraS3Response deleteObjectCachedNotificationRegistrationSpectraS3(DeleteObjectCachedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteObjectLostNotificationRegistrationSpectraS3Response deleteObjectLostNotificationRegistrationSpectraS3(DeleteObjectLostNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteObjectPersistedNotificationRegistrationSpectraS3Response deleteObjectPersistedNotificationRegistrationSpectraS3(DeleteObjectPersistedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    DeletePoolFailureNotificationRegistrationSpectraS3Response deletePoolFailureNotificationRegistrationSpectraS3(DeletePoolFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteStorageDomainFailureNotificationRegistrationSpectraS3Response deleteStorageDomainFailureNotificationRegistrationSpectraS3(DeleteStorageDomainFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteSystemFailureNotificationRegistrationSpectraS3Response deleteSystemFailureNotificationRegistrationSpectraS3(DeleteSystemFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteTapeFailureNotificationRegistrationSpectraS3Response deleteTapeFailureNotificationRegistrationSpectraS3(DeleteTapeFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteTapePartitionFailureNotificationRegistrationSpectraS3Response deleteTapePartitionFailureNotificationRegistrationSpectraS3(DeleteTapePartitionFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetDs3TargetFailureNotificationRegistrationSpectraS3Response getDs3TargetFailureNotificationRegistrationSpectraS3(GetDs3TargetFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetDs3TargetFailureNotificationRegistrationsSpectraS3Response getDs3TargetFailureNotificationRegistrationsSpectraS3(GetDs3TargetFailureNotificationRegistrationsSpectraS3Request request)
            throws IOException, SignatureException;
    GetJobCompletedNotificationRegistrationSpectraS3Response getJobCompletedNotificationRegistrationSpectraS3(GetJobCompletedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetJobCompletedNotificationRegistrationsSpectraS3Response getJobCompletedNotificationRegistrationsSpectraS3(GetJobCompletedNotificationRegistrationsSpectraS3Request request)
            throws IOException, SignatureException;
    GetJobCreatedNotificationRegistrationSpectraS3Response getJobCreatedNotificationRegistrationSpectraS3(GetJobCreatedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetJobCreatedNotificationRegistrationsSpectraS3Response getJobCreatedNotificationRegistrationsSpectraS3(GetJobCreatedNotificationRegistrationsSpectraS3Request request)
            throws IOException, SignatureException;
    GetObjectCachedNotificationRegistrationSpectraS3Response getObjectCachedNotificationRegistrationSpectraS3(GetObjectCachedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetObjectCachedNotificationRegistrationsSpectraS3Response getObjectCachedNotificationRegistrationsSpectraS3(GetObjectCachedNotificationRegistrationsSpectraS3Request request)
            throws IOException, SignatureException;
    GetObjectLostNotificationRegistrationSpectraS3Response getObjectLostNotificationRegistrationSpectraS3(GetObjectLostNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetObjectLostNotificationRegistrationsSpectraS3Response getObjectLostNotificationRegistrationsSpectraS3(GetObjectLostNotificationRegistrationsSpectraS3Request request)
            throws IOException, SignatureException;
    GetObjectPersistedNotificationRegistrationSpectraS3Response getObjectPersistedNotificationRegistrationSpectraS3(GetObjectPersistedNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetObjectPersistedNotificationRegistrationsSpectraS3Response getObjectPersistedNotificationRegistrationsSpectraS3(GetObjectPersistedNotificationRegistrationsSpectraS3Request request)
            throws IOException, SignatureException;
    GetPoolFailureNotificationRegistrationSpectraS3Response getPoolFailureNotificationRegistrationSpectraS3(GetPoolFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetPoolFailureNotificationRegistrationsSpectraS3Response getPoolFailureNotificationRegistrationsSpectraS3(GetPoolFailureNotificationRegistrationsSpectraS3Request request)
            throws IOException, SignatureException;
    GetStorageDomainFailureNotificationRegistrationSpectraS3Response getStorageDomainFailureNotificationRegistrationSpectraS3(GetStorageDomainFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetStorageDomainFailureNotificationRegistrationsSpectraS3Response getStorageDomainFailureNotificationRegistrationsSpectraS3(GetStorageDomainFailureNotificationRegistrationsSpectraS3Request request)
            throws IOException, SignatureException;
    GetSystemFailureNotificationRegistrationSpectraS3Response getSystemFailureNotificationRegistrationSpectraS3(GetSystemFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetSystemFailureNotificationRegistrationsSpectraS3Response getSystemFailureNotificationRegistrationsSpectraS3(GetSystemFailureNotificationRegistrationsSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapeFailureNotificationRegistrationSpectraS3Response getTapeFailureNotificationRegistrationSpectraS3(GetTapeFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapeFailureNotificationRegistrationsSpectraS3Response getTapeFailureNotificationRegistrationsSpectraS3(GetTapeFailureNotificationRegistrationsSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapePartitionFailureNotificationRegistrationSpectraS3Response getTapePartitionFailureNotificationRegistrationSpectraS3(GetTapePartitionFailureNotificationRegistrationSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapePartitionFailureNotificationRegistrationsSpectraS3Response getTapePartitionFailureNotificationRegistrationsSpectraS3(GetTapePartitionFailureNotificationRegistrationsSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteFolderRecursivelySpectraS3Response deleteFolderRecursivelySpectraS3(DeleteFolderRecursivelySpectraS3Request request)
            throws IOException, SignatureException;
    GetObjectSpectraS3Response getObjectSpectraS3(GetObjectSpectraS3Request request)
            throws IOException, SignatureException;
    GetObjectsSpectraS3Response getObjectsSpectraS3(GetObjectsSpectraS3Request request)
            throws IOException, SignatureException;
    GetObjectsWithFullDetailsSpectraS3Response getObjectsWithFullDetailsSpectraS3(GetObjectsWithFullDetailsSpectraS3Request request)
            throws IOException, SignatureException;
    GetPhysicalPlacementForObjectsSpectraS3Response getPhysicalPlacementForObjectsSpectraS3(GetPhysicalPlacementForObjectsSpectraS3Request request)
            throws IOException, SignatureException;
    GetPhysicalPlacementForObjectsWithFullDetailsSpectraS3Response getPhysicalPlacementForObjectsWithFullDetailsSpectraS3(GetPhysicalPlacementForObjectsWithFullDetailsSpectraS3Request request)
            throws IOException, SignatureException;
    VerifyPhysicalPlacementForObjectsSpectraS3Response verifyPhysicalPlacementForObjectsSpectraS3(VerifyPhysicalPlacementForObjectsSpectraS3Request request)
            throws IOException, SignatureException;
    VerifyPhysicalPlacementForObjectsWithFullDetailsSpectraS3Response verifyPhysicalPlacementForObjectsWithFullDetailsSpectraS3(VerifyPhysicalPlacementForObjectsWithFullDetailsSpectraS3Request request)
            throws IOException, SignatureException;
    CancelImportOnAllPoolsSpectraS3Response cancelImportOnAllPoolsSpectraS3(CancelImportOnAllPoolsSpectraS3Request request)
            throws IOException, SignatureException;
    CancelImportPoolSpectraS3Response cancelImportPoolSpectraS3(CancelImportPoolSpectraS3Request request)
            throws IOException, SignatureException;
    CompactAllPoolsSpectraS3Response compactAllPoolsSpectraS3(CompactAllPoolsSpectraS3Request request)
            throws IOException, SignatureException;
    CompactPoolSpectraS3Response compactPoolSpectraS3(CompactPoolSpectraS3Request request)
            throws IOException, SignatureException;
    PutPoolPartitionSpectraS3Response putPoolPartitionSpectraS3(PutPoolPartitionSpectraS3Request request)
            throws IOException, SignatureException;
    DeallocatePoolSpectraS3Response deallocatePoolSpectraS3(DeallocatePoolSpectraS3Request request)
            throws IOException, SignatureException;
    DeletePermanentlyLostPoolSpectraS3Response deletePermanentlyLostPoolSpectraS3(DeletePermanentlyLostPoolSpectraS3Request request)
            throws IOException, SignatureException;
    DeletePoolFailureSpectraS3Response deletePoolFailureSpectraS3(DeletePoolFailureSpectraS3Request request)
            throws IOException, SignatureException;
    DeletePoolPartitionSpectraS3Response deletePoolPartitionSpectraS3(DeletePoolPartitionSpectraS3Request request)
            throws IOException, SignatureException;
    ForcePoolEnvironmentRefreshSpectraS3Response forcePoolEnvironmentRefreshSpectraS3(ForcePoolEnvironmentRefreshSpectraS3Request request)
            throws IOException, SignatureException;
    FormatAllForeignPoolsSpectraS3Response formatAllForeignPoolsSpectraS3(FormatAllForeignPoolsSpectraS3Request request)
            throws IOException, SignatureException;
    FormatForeignPoolSpectraS3Response formatForeignPoolSpectraS3(FormatForeignPoolSpectraS3Request request)
            throws IOException, SignatureException;
    GetBlobsOnPoolSpectraS3Response getBlobsOnPoolSpectraS3(GetBlobsOnPoolSpectraS3Request request)
            throws IOException, SignatureException;
    GetPoolFailuresSpectraS3Response getPoolFailuresSpectraS3(GetPoolFailuresSpectraS3Request request)
            throws IOException, SignatureException;
    GetPoolPartitionSpectraS3Response getPoolPartitionSpectraS3(GetPoolPartitionSpectraS3Request request)
            throws IOException, SignatureException;
    GetPoolPartitionsSpectraS3Response getPoolPartitionsSpectraS3(GetPoolPartitionsSpectraS3Request request)
            throws IOException, SignatureException;
    GetPoolSpectraS3Response getPoolSpectraS3(GetPoolSpectraS3Request request)
            throws IOException, SignatureException;
    GetPoolsSpectraS3Response getPoolsSpectraS3(GetPoolsSpectraS3Request request)
            throws IOException, SignatureException;
    ImportAllPoolsSpectraS3Response importAllPoolsSpectraS3(ImportAllPoolsSpectraS3Request request)
            throws IOException, SignatureException;
    ImportPoolSpectraS3Response importPoolSpectraS3(ImportPoolSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyAllPoolsSpectraS3Response modifyAllPoolsSpectraS3(ModifyAllPoolsSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyPoolPartitionSpectraS3Response modifyPoolPartitionSpectraS3(ModifyPoolPartitionSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyPoolSpectraS3Response modifyPoolSpectraS3(ModifyPoolSpectraS3Request request)
            throws IOException, SignatureException;
    VerifyAllPoolsSpectraS3Response verifyAllPoolsSpectraS3(VerifyAllPoolsSpectraS3Request request)
            throws IOException, SignatureException;
    VerifyPoolSpectraS3Response verifyPoolSpectraS3(VerifyPoolSpectraS3Request request)
            throws IOException, SignatureException;
    PutPoolStorageDomainMemberSpectraS3Response putPoolStorageDomainMemberSpectraS3(PutPoolStorageDomainMemberSpectraS3Request request)
            throws IOException, SignatureException;
    PutStorageDomainSpectraS3Response putStorageDomainSpectraS3(PutStorageDomainSpectraS3Request request)
            throws IOException, SignatureException;
    PutTapeStorageDomainMemberSpectraS3Response putTapeStorageDomainMemberSpectraS3(PutTapeStorageDomainMemberSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteStorageDomainFailureSpectraS3Response deleteStorageDomainFailureSpectraS3(DeleteStorageDomainFailureSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteStorageDomainMemberSpectraS3Response deleteStorageDomainMemberSpectraS3(DeleteStorageDomainMemberSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteStorageDomainSpectraS3Response deleteStorageDomainSpectraS3(DeleteStorageDomainSpectraS3Request request)
            throws IOException, SignatureException;
    GetStorageDomainFailuresSpectraS3Response getStorageDomainFailuresSpectraS3(GetStorageDomainFailuresSpectraS3Request request)
            throws IOException, SignatureException;
    GetStorageDomainMemberSpectraS3Response getStorageDomainMemberSpectraS3(GetStorageDomainMemberSpectraS3Request request)
            throws IOException, SignatureException;
    GetStorageDomainMembersSpectraS3Response getStorageDomainMembersSpectraS3(GetStorageDomainMembersSpectraS3Request request)
            throws IOException, SignatureException;
    GetStorageDomainSpectraS3Response getStorageDomainSpectraS3(GetStorageDomainSpectraS3Request request)
            throws IOException, SignatureException;
    GetStorageDomainsSpectraS3Response getStorageDomainsSpectraS3(GetStorageDomainsSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyStorageDomainMemberSpectraS3Response modifyStorageDomainMemberSpectraS3(ModifyStorageDomainMemberSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyStorageDomainSpectraS3Response modifyStorageDomainSpectraS3(ModifyStorageDomainSpectraS3Request request)
            throws IOException, SignatureException;
    GetSystemFailuresSpectraS3Response getSystemFailuresSpectraS3(GetSystemFailuresSpectraS3Request request)
            throws IOException, SignatureException;
    GetSystemInformationSpectraS3Response getSystemInformationSpectraS3(GetSystemInformationSpectraS3Request request)
            throws IOException, SignatureException;
    ResetInstanceIdentifierSpectraS3Response resetInstanceIdentifierSpectraS3(ResetInstanceIdentifierSpectraS3Request request)
            throws IOException, SignatureException;
    VerifySystemHealthSpectraS3Response verifySystemHealthSpectraS3(VerifySystemHealthSpectraS3Request request)
            throws IOException, SignatureException;
    CancelEjectOnAllTapesSpectraS3Response cancelEjectOnAllTapesSpectraS3(CancelEjectOnAllTapesSpectraS3Request request)
            throws IOException, SignatureException;
    CancelEjectTapeSpectraS3Response cancelEjectTapeSpectraS3(CancelEjectTapeSpectraS3Request request)
            throws IOException, SignatureException;
    CancelFormatOnAllTapesSpectraS3Response cancelFormatOnAllTapesSpectraS3(CancelFormatOnAllTapesSpectraS3Request request)
            throws IOException, SignatureException;
    CancelFormatTapeSpectraS3Response cancelFormatTapeSpectraS3(CancelFormatTapeSpectraS3Request request)
            throws IOException, SignatureException;
    CancelImportOnAllTapesSpectraS3Response cancelImportOnAllTapesSpectraS3(CancelImportOnAllTapesSpectraS3Request request)
            throws IOException, SignatureException;
    CancelImportTapeSpectraS3Response cancelImportTapeSpectraS3(CancelImportTapeSpectraS3Request request)
            throws IOException, SignatureException;
    CancelOnlineOnAllTapesSpectraS3Response cancelOnlineOnAllTapesSpectraS3(CancelOnlineOnAllTapesSpectraS3Request request)
            throws IOException, SignatureException;
    CancelOnlineTapeSpectraS3Response cancelOnlineTapeSpectraS3(CancelOnlineTapeSpectraS3Request request)
            throws IOException, SignatureException;
    CancelVerifyOnAllTapesSpectraS3Response cancelVerifyOnAllTapesSpectraS3(CancelVerifyOnAllTapesSpectraS3Request request)
            throws IOException, SignatureException;
    CancelVerifyTapeSpectraS3Response cancelVerifyTapeSpectraS3(CancelVerifyTapeSpectraS3Request request)
            throws IOException, SignatureException;
    CleanTapeDriveSpectraS3Response cleanTapeDriveSpectraS3(CleanTapeDriveSpectraS3Request request)
            throws IOException, SignatureException;
    PutTapeDensityDirectiveSpectraS3Response putTapeDensityDirectiveSpectraS3(PutTapeDensityDirectiveSpectraS3Request request)
            throws IOException, SignatureException;
    DeletePermanentlyLostTapeSpectraS3Response deletePermanentlyLostTapeSpectraS3(DeletePermanentlyLostTapeSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteTapeDensityDirectiveSpectraS3Response deleteTapeDensityDirectiveSpectraS3(DeleteTapeDensityDirectiveSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteTapeDriveSpectraS3Response deleteTapeDriveSpectraS3(DeleteTapeDriveSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteTapeFailureSpectraS3Response deleteTapeFailureSpectraS3(DeleteTapeFailureSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteTapePartitionFailureSpectraS3Response deleteTapePartitionFailureSpectraS3(DeleteTapePartitionFailureSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteTapePartitionSpectraS3Response deleteTapePartitionSpectraS3(DeleteTapePartitionSpectraS3Request request)
            throws IOException, SignatureException;
    EjectAllTapesSpectraS3Response ejectAllTapesSpectraS3(EjectAllTapesSpectraS3Request request)
            throws IOException, SignatureException;
    EjectStorageDomainBlobsSpectraS3Response ejectStorageDomainBlobsSpectraS3(EjectStorageDomainBlobsSpectraS3Request request)
            throws IOException, SignatureException;
    EjectStorageDomainSpectraS3Response ejectStorageDomainSpectraS3(EjectStorageDomainSpectraS3Request request)
            throws IOException, SignatureException;
    EjectTapeSpectraS3Response ejectTapeSpectraS3(EjectTapeSpectraS3Request request)
            throws IOException, SignatureException;
    ForceTapeEnvironmentRefreshSpectraS3Response forceTapeEnvironmentRefreshSpectraS3(ForceTapeEnvironmentRefreshSpectraS3Request request)
            throws IOException, SignatureException;
    FormatAllTapesSpectraS3Response formatAllTapesSpectraS3(FormatAllTapesSpectraS3Request request)
            throws IOException, SignatureException;
    FormatTapeSpectraS3Response formatTapeSpectraS3(FormatTapeSpectraS3Request request)
            throws IOException, SignatureException;
    GetBlobsOnTapeSpectraS3Response getBlobsOnTapeSpectraS3(GetBlobsOnTapeSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapeDensityDirectiveSpectraS3Response getTapeDensityDirectiveSpectraS3(GetTapeDensityDirectiveSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapeDensityDirectivesSpectraS3Response getTapeDensityDirectivesSpectraS3(GetTapeDensityDirectivesSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapeDriveSpectraS3Response getTapeDriveSpectraS3(GetTapeDriveSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapeDrivesSpectraS3Response getTapeDrivesSpectraS3(GetTapeDrivesSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapeFailuresSpectraS3Response getTapeFailuresSpectraS3(GetTapeFailuresSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapeLibrariesSpectraS3Response getTapeLibrariesSpectraS3(GetTapeLibrariesSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapeLibrarySpectraS3Response getTapeLibrarySpectraS3(GetTapeLibrarySpectraS3Request request)
            throws IOException, SignatureException;
    GetTapePartitionFailuresSpectraS3Response getTapePartitionFailuresSpectraS3(GetTapePartitionFailuresSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapePartitionSpectraS3Response getTapePartitionSpectraS3(GetTapePartitionSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapePartitionWithFullDetailsSpectraS3Response getTapePartitionWithFullDetailsSpectraS3(GetTapePartitionWithFullDetailsSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapePartitionsSpectraS3Response getTapePartitionsSpectraS3(GetTapePartitionsSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapePartitionsWithFullDetailsSpectraS3Response getTapePartitionsWithFullDetailsSpectraS3(GetTapePartitionsWithFullDetailsSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapeSpectraS3Response getTapeSpectraS3(GetTapeSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapeWithFullDetailsSpectraS3Response getTapeWithFullDetailsSpectraS3(GetTapeWithFullDetailsSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapesSpectraS3Response getTapesSpectraS3(GetTapesSpectraS3Request request)
            throws IOException, SignatureException;
    GetTapesWithFullDetailsSpectraS3Response getTapesWithFullDetailsSpectraS3(GetTapesWithFullDetailsSpectraS3Request request)
            throws IOException, SignatureException;
    ImportAllTapesSpectraS3Response importAllTapesSpectraS3(ImportAllTapesSpectraS3Request request)
            throws IOException, SignatureException;
    ImportTapeSpectraS3Response importTapeSpectraS3(ImportTapeSpectraS3Request request)
            throws IOException, SignatureException;
    InspectAllTapesSpectraS3Response inspectAllTapesSpectraS3(InspectAllTapesSpectraS3Request request)
            throws IOException, SignatureException;
    InspectTapeSpectraS3Response inspectTapeSpectraS3(InspectTapeSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyAllTapePartitionsSpectraS3Response modifyAllTapePartitionsSpectraS3(ModifyAllTapePartitionsSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyTapePartitionSpectraS3Response modifyTapePartitionSpectraS3(ModifyTapePartitionSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyTapeSpectraS3Response modifyTapeSpectraS3(ModifyTapeSpectraS3Request request)
            throws IOException, SignatureException;
    OnlineAllTapesSpectraS3Response onlineAllTapesSpectraS3(OnlineAllTapesSpectraS3Request request)
            throws IOException, SignatureException;
    OnlineTapeSpectraS3Response onlineTapeSpectraS3(OnlineTapeSpectraS3Request request)
            throws IOException, SignatureException;
    VerifyAllTapesSpectraS3Response verifyAllTapesSpectraS3(VerifyAllTapesSpectraS3Request request)
            throws IOException, SignatureException;
    VerifyTapeSpectraS3Response verifyTapeSpectraS3(VerifyTapeSpectraS3Request request)
            throws IOException, SignatureException;
    PutDs3TargetReadPreferenceSpectraS3Response putDs3TargetReadPreferenceSpectraS3(PutDs3TargetReadPreferenceSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteDs3TargetFailureSpectraS3Response deleteDs3TargetFailureSpectraS3(DeleteDs3TargetFailureSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteDs3TargetReadPreferenceSpectraS3Response deleteDs3TargetReadPreferenceSpectraS3(DeleteDs3TargetReadPreferenceSpectraS3Request request)
            throws IOException, SignatureException;
    DeleteDs3TargetSpectraS3Response deleteDs3TargetSpectraS3(DeleteDs3TargetSpectraS3Request request)
            throws IOException, SignatureException;
    GetDs3TargetFailuresSpectraS3Response getDs3TargetFailuresSpectraS3(GetDs3TargetFailuresSpectraS3Request request)
            throws IOException, SignatureException;
    GetDs3TargetReadPreferenceSpectraS3Response getDs3TargetReadPreferenceSpectraS3(GetDs3TargetReadPreferenceSpectraS3Request request)
            throws IOException, SignatureException;
    GetDs3TargetReadPreferencesSpectraS3Response getDs3TargetReadPreferencesSpectraS3(GetDs3TargetReadPreferencesSpectraS3Request request)
            throws IOException, SignatureException;
    GetDs3TargetSpectraS3Response getDs3TargetSpectraS3(GetDs3TargetSpectraS3Request request)
            throws IOException, SignatureException;
    GetDs3TargetsSpectraS3Response getDs3TargetsSpectraS3(GetDs3TargetsSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyAllDs3TargetsSpectraS3Response modifyAllDs3TargetsSpectraS3(ModifyAllDs3TargetsSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyDs3TargetSpectraS3Response modifyDs3TargetSpectraS3(ModifyDs3TargetSpectraS3Request request)
            throws IOException, SignatureException;
    PairBackRegisteredDs3TargetSpectraS3Response pairBackRegisteredDs3TargetSpectraS3(PairBackRegisteredDs3TargetSpectraS3Request request)
            throws IOException, SignatureException;
    RegisterDs3TargetSpectraS3Response registerDs3TargetSpectraS3(RegisterDs3TargetSpectraS3Request request)
            throws IOException, SignatureException;
    VerifyDs3TargetSpectraS3Response verifyDs3TargetSpectraS3(VerifyDs3TargetSpectraS3Request request)
            throws IOException, SignatureException;
    DelegateCreateUserSpectraS3Response delegateCreateUserSpectraS3(DelegateCreateUserSpectraS3Request request)
            throws IOException, SignatureException;
    DelegateDeleteUserSpectraS3Response delegateDeleteUserSpectraS3(DelegateDeleteUserSpectraS3Request request)
            throws IOException, SignatureException;
    GetUserSpectraS3Response getUserSpectraS3(GetUserSpectraS3Request request)
            throws IOException, SignatureException;
    GetUsersSpectraS3Response getUsersSpectraS3(GetUsersSpectraS3Request request)
            throws IOException, SignatureException;
    ModifyUserSpectraS3Response modifyUserSpectraS3(ModifyUserSpectraS3Request request)
            throws IOException, SignatureException;
    RegenerateUserSecretKeySpectraS3Response regenerateUserSecretKeySpectraS3(RegenerateUserSecretKeySpectraS3Request request)
            throws IOException, SignatureException;
    GetObjectResponse getObject(GetObjectRequest request)
            throws IOException, SignatureException;

    Ds3Client newForNode(final Ds3Node node);
}