name: DS3 Java SDK Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'
          check-latest: true
      - name: Run PR Tests
        run: ./gradlew -S clean jar :ds3-sdk:test :ds3-utils:test :ds3-metadata:test
